version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    id: "parca-load"
    binary: parca-load
    # https://goreleaser.com/customization/build/#reproducible-builds
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -v
    ldflags:
      # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
      - -X main.version={{.Version}} -X main.commit={{.Commit}}
archives:
    # e.g. parca_0.15.0_Darwin_arm64.tar.gz, parca_0.15.0_Darwin_x86_64.tar.gz, parca_0.15.0_Linux_arm64.tar.gz, parca_0.15.0_Linux_x86_64.tar.gz
  - name_template: >-
      {{ .ProjectName }}_
      {{- trimprefix .Version "v" }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']
checksum:
  name_template: "checksums.txt"
source:
  enabled: true

# Build container images using Ko
# https://goreleaser.com/customization/ko/
kos:
  - id: parca-load
    build: parca-load
    # Use distroless static base for minimal attack surface
    base_image: gcr.io/distroless/static-debian12:nonroot
    repository: ghcr.io/parca-dev/parca-load
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "{{ if .IsSnapshot }}{{ .Branch }}-{{ .ShortCommit }}{{ else }}{{ .Version }}{{ end }}"
      - "{{ if not .IsSnapshot }}latest{{ end }}"
    sbom: none
    bare: true
    preserve_import_paths: false
    labels:
      org.opencontainers.image.source: https://github.com/parca-dev/parca-load
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.licenses: Apache-2.0

# Sign container manifests with Cosign
docker_signs:
  - artifacts: manifests
    args:
      - sign
      - --yes
      - -a
      - "GIT_HASH={{ .ShortCommit }}"
      - -a
      - "GIT_VERSION={{ .Version }}"
      - "${artifact}@${digest}"
